### ISSUE TITLE
MTC4BT: Locos do not resume their last received light (fn) command

### ISSUE THREAD

**Issue by Mattzobricks** [Mattzobricks/MattzoControllers#19]
Locos do not resume their last received fn command when initially connected. An additional Rocrail fn command is required to get the light on or off. To overcome this problem, you could set the presently desired fn state for the loco right after connecting to all BLE hubs of that loco. For this reason it is required that you actually store the last received fn command within the MTC4BT for each loco.

As always, auto lights shall supersede the manual light command.

Related issues (from the old repo):
#16 (same for motors).
#19 (behaviour after partial disconnect).

**Comment by Mattzobricks** [comment]
The same applies for auto light commands there are executed when not all motors are connected. Compare #16 for a more detailed description.

**Comment by raymondbrink** [comment]
@Mattzobricks Same request here: Would you mind testing if the fix in this branch resolves the issue with handling light commands when at least on hub is not connected (yet)?

**Comment by Mattzobricks** [comment]
Successfully tested. Please rebase on develop before merging.

**Comment by raymondbrink** [comment]
There are no conflicts to merge it into develop directly. Pull request submitted.

**Comment by Mattzobricks** [comment]
Approved, thank you.
