### ISSUE TITLE
MCT4BT: ebreak always has to come through!

### ISSUE THREAD

**Issue by Hilbert70** [Mattzobricks/MattzoControllers#33]
Do not check for AllHubsCOnnected, we should change it to:
ForAllHubsConnected....
```
void BLELocomotive::SetEmergencyBrake(const bool enabled)
{
    if (!AllHubsConnected()) {
        // Ignore e-brake command (we're not driving anyway).
        return;
    }

    // Handle e-brake on all channels of our hubs.
    for (BLEHub *hub : Hubs) {
        hub->EmergencyBrake(enabled);
    }
}
```

**Comment by raymondbrink** [comment]
This is fixed with #20.

**Comment by raymondbrink** [comment]
@Hilbert70 #20 was resolved and merged into develop just before X-mas. Would you mind checking if this is resolved now?

**Comment by Mattzobricks** [comment]
Successfully tested.

Test:
- ICE train, two locos.
- Started locos. Both motors revolve.
- Powered down one loco. Both motors stop.
- Hit the emergency brake in Rocrail.
- Reconnected the loco that was powered down. Both locos remain in emergency brake mode.
- Repowering the layout in Rocrail makes the train take off immediately.

Works as expected.

Closing issue.
