### ISSUE TITLE
MTC4BT memory leak

### ISSUE THREAD

**Issue by Mattzobricks** [Mattzobricks/MattzoControllers#34]
The debug option introduced by Hilbert shows that we still have a memory leak. The controller works on a complex layout with 4 connected devices for a couple of hours. Thereafter, no memory is left and the controller crashes.

**Comment by Hilbert70** [comment]
Should be fixed in https://github.com/Mattzobricks/MattzoControllers/pull/50
 #50

**Comment by Mattzobricks** [comment]
Hi Hilbert! I checked out commit d7b2a8d8d1523b35603e7cf83b04881994574b43 on branch "feature_memory_debug".

The configuration contains 2 SBricks and 2 Powered Up hubs.

Unfortunately, the controller crashes after 2 minutes:

[0086] [1] Minutes uptime: 2.00
[0087] [1]   Memory Heap free:   136308 max alloc:    97436 min free:   128516
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400d424e  PS      : 0x00060730  A0      : 0x8018762a  A1      : 0x3ffcc9e0
A2      : 0x00000000  A3      : 0x3ffe382d  A4      : 0xffffde00  A5      : 0x00000758
A6      : 0x3ffe8bcc  A7      : 0x3ffcab60  A8      : 0x00000000  A9      : 0x000000d4
A10     : 0x3ffe162c  A11     : 0x40086630  A12     : 0x3ffc3df0  A13     : 0x00000000
A14     : 0x3ffc9278  A15     : 0x3ffc9278  SAR     : 0x0000000a  EXCCAUSE: 0x0000001d
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff

ELF file SHA256: 0000000000000000

Backtrace: 0x400d424e:0x3ffcc9e0 0x40187627:0x3ffcca00 0x4013208e:0x3ffcca20 0x400ec48e:0x3ffcca60 0x400d43d3:0x3ffcca80 0x400ef8b1:0x3ffccaa0 0x400908fa:0x3ffccac0

Rebooting...
ets Jun  8 2016 00:22:57

**Comment by Mattzobricks** [comment]
I have isolated the memory leak fix from the mentioned branch. With just the fix, everything seems to work stable after one hour on continuous, high traffic operation with 4 connected BLE devices. I will commit this fix and close this issue.
