### ISSUE TITLE
MTC4BT: Large controller_config.json files crash the controller at start-up

### ISSUE THREAD

**Issue by raymondbrink** [Mattzobricks/MattzoControllers#6]
We should find a way to handle larger (10k+) controller_config.json files.

**Comment by raymondbrink** [comment]
And? Any news on this attempt?

**Comment by Mattzobricks** [comment]
Last time I tried we still had the problem.

**Comment by Hilbert70** [comment]
Could not get it to work reliably.

**Comment by Mattzobricks** [comment]
After discussion between Ray, Hilbert and Mattze:
- we are going to split the controller_config.json file into separate files; one for the general configuration (controller_config.json), one for each loco (loco_config*.json).
- the change is backward compatible. Locos can still remain in the general configuration file.

**Comment by Mattzobricks** [comment]
Tested it. Works fine.
