### ISSUE TITLE
[my_common] is missing in my_platformio.ini.example

### ISSUE THREAD

**Issue by Hilbert70** [Mattzobricks/MattzoControllers#61]
Please add an empty [my_common] in the example, the my_common should still be there because I saw that platformio is not merging the same variables from the platformio.ini and my_platformio.ini
Example
platformio.ini 
```
[common]
some_flag = foo
```
my_platformio.ini
```
[common]
some_flag = bar
```

The resulting some_flag is not ```foo bar```, but either ```foo``` or ```bar```

To make sure this example is doing what you expect it to do:
platformio.ini 
```
[common]
some_flag = foo ${my_common.some_flag}
```
my_platformio.ini
```
[my_common]
some_flag = bar
```

This will result in some_flag having the value ```foo bar```

Make sure to test is with an empty ```some_flag``` section in ```[my_common]```

**Comment by Mattzobricks** [comment]
@Hilbert70, is this done?
