### ISSUE TITLE
MTC4BT: Unify alternative direction label in config between channels and actions

### ISSUE THREAD

**Issue by raymondbrink** [Mattzobricks/MattzoControllers#8]
Channels now expect a value of `reverse` for the alternate direction. Actions require `backward`. Both should use the same value.

**Comment by Mattzobricks** [comment]
It might be a good idea to remain backwards compatible when implementing this change, so user configuration will not fail after the firmware upgrade.

**Comment by Mattzobricks** [comment]
To Dos:
- choose one keyword.
- support both in code.
- change documentation and example to to the chosen keyword.

**Comment by raymondbrink** [comment]
The keyword will be "backward", so:
