### ISSUE TITLE
MQTT broker does not recognize the hostname of the MTC4BT when connected via Ethernet

### ISSUE THREAD

**Issue by Mattzobricks** [Mattzobricks/MattzoControllers#97]
There might be a problem with the wired option. The MQTT broker does no longer recognize the name of the client. It is "unknown" to the MQTT broker. Is it possible that the hostname of the MTC4BT is not correctly set when connecting to the network?

**Comment by Hilbert70** [comment]
Can't be done in this implementation, should automatic work if we switch to the ETH or ETHclass implementation
